# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-06 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo_Skill',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_f_normal_s2', models.IntegerField(blank=True, null=True)),
                ('upper_f_normal_s2', models.IntegerField(blank=True, null=True)),
                ('end_f_normal_s2', models.IntegerField(blank=True, null=True)),
                ('start_m_normal_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('upper_m_normal_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('end_m_normal_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_shield_pass_s2', models.BooleanField()),
                ('is_debuff_pass_s2', models.BooleanField()),
                ('start_f_special_s2', models.IntegerField(blank=True, null=True)),
                ('upper_f_special_s2', models.IntegerField(blank=True, null=True)),
                ('end_f_special_s2', models.IntegerField(blank=True, null=True)),
                ('start_m_special_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('upper_m_special_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('end_m_special_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('barrier_s2', models.IntegerField(blank=True, null=True)),
                ('barrier_return_s2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('barrier_type_s2', models.CharField(max_length=10)),
                ('upper_m_type_s2', models.CharField(blank=True, max_length=10, null=True)),
                ('target_type_s2', models.CharField(blank=True, max_length=10, null=True)),
                ('summons_s2', models.CharField(blank=True, max_length=50, null=True)),
                ('active_turn_s2', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('debuff', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('coercion', models.IntegerField(blank=True, null=True)),
                ('normal_cut', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('special_cut', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cut_type', models.CharField(max_length=10)),
                ('active_turn', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_f_normal_s1', models.IntegerField(blank=True, null=True)),
                ('upper_f_normal_s1', models.IntegerField(blank=True, null=True)),
                ('end_f_normal_s1', models.IntegerField(blank=True, null=True)),
                ('start_m_normal_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('upper_m_normal_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('end_m_normal_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_shield_pass_s1', models.BooleanField()),
                ('is_debuff_pass_s1', models.BooleanField()),
                ('start_f_special_s1', models.IntegerField(blank=True, null=True)),
                ('upper_f_special_s1', models.IntegerField(blank=True, null=True)),
                ('end_f_special_s1', models.IntegerField(blank=True, null=True)),
                ('start_m_special_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('upper_m_special_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('end_m_special_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('barrier_s1', models.IntegerField(blank=True, null=True)),
                ('barrier_return_s1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('barrier_type_s1', models.CharField(max_length=10)),
                ('upper_m_type_s1', models.CharField(blank=True, max_length=10, null=True)),
                ('target_type_s1', models.CharField(blank=True, max_length=10, null=True)),
                ('summons_s1', models.CharField(blank=True, max_length=50, null=True)),
                ('active_turn_s1', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField()),
                ('rarity', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othello_apps.Status'),
        ),
        migrations.AddField(
            model_name='combo_skill',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othello_apps.Status'),
        ),
    ]
